<a href="https://colab.research.google.com/github/25wh1a0518/NASSCOM/blob/main/WEEK_2_Exercise_U3_Python_Part2_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix

sns.set_theme(style='whitegrid')   # nicer default plot styling
np.random.seed(42)                 # reproducible results
print('Setup complete. NumPy', np.__version__, '| Pandas', pd.__version__)


Setup complete. NumPy 2.0.2 | Pandas 2.2.2


In [ ]:
import numpy as np


# Given data
M = np.arange(1, 13).reshape(3, 4)   # shape (3, 4)
N = np.arange(1, 9).reshape(4, 2)    # shape (4, 2)
print('M:\n', M)
print('N:\n', N)

# 1. Matrix product M @ N
print('matrix multiplication:',M@N)
# 2. Column-wise sum (axis=0) and row-wise mean (axis=1) of M
print('coloumn wise sum:',np.sum(M,axis=0))
print('row-wise mean',np.mean(M,axis=1))
# 3. Index of the max value in each row of M (hint: argmax with axis=1)
print('max index:',np.argmax(M,axis=1))



M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
N:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
matrix multiplication: [[ 50  60]
 [114 140]
 [178 220]]
coloumn wise sum: [15 18 21 24]
row-wise mean [ 2.5  6.5 10.5]
max index: [3 3 3]


In [ ]:
from IPython.core.profiledir import observe
lab = sns.load_dataset('titanic')   # fresh copy to work on

print('\n missing embarked values:',lab['embarked'].isna().sum())
lab['embarked']=lab['embarked'].fillna(lab['embarked'].mode()[0])
print('\n missing values:',lab['embarked'].isna().sum())
print('\n mean fare grouped by sex:')
print(lab.groupby('sex',observed=True)['fare'].mean())


 missing embarked values: 2

 missing values: 0

 mean fare grouped by sex:
sex
female    44.479818
male      25.523893
Name: fare, dtype: float64


In [4]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


Xb, yb = load_breast_cancer(return_X_y=True)
print('Breast cancer data:', Xb.shape)


X_train, X_test, y_train, y_test = train_test_split(
    Xb,
    yb,
    test_size=0.25,
    random_state=0,
    stratify=yb
)


pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(random_state=0))
])


pipe.fit(X_train, y_train)
print("Test accuracy:", pipe.score(X_test, y_test))

Breast cancer data: (569, 30)
Test accuracy: 0.958041958041958
