<a href="https://colab.research.google.com/github/25wh1a0518/NASSCOM/blob/main/WEEK_2_NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, (5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[10 23 13 46 44]
 [44 35 36 12 25]]


In [ ]:
import numpy as np

print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1=data[2,3]
row2_2=data[0]
col2_3=data[3]
sub_arr2_4=data[1:3,0:2]
filtered_elements2_5=data[data>100]
print("value of row2 and coloumn 3",val2_1)
print("first row",row2_2)
print("last coloumn",col2_3)
print("sub_array",sub_arr2_4)
print("filtered elements are",filtered_elements2_5)



--- Task 2: Indexing and Slicing with Arrays ---
value of row2 and coloumn 3 120
first row [10 20 30 40]
last coloumn [130 140 150 160]
sub_array [[ 50  60]
 [ 90 100]]
filtered elements are [110 120 130 140 150 160]


In [ ]:
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
arr3_2=np.where(arr3_1<10,0,arr3_1)
even_count3_3=np.sum(arr3_2%2==0)
print("array:",arr3_2)
print("enter the even numbers:",even_count3_3)



--- Task 3: Conditional Operations ---
array: [[16  0 10 20 18]
 [18  0 13  0  0]
 [ 0 12 16 17 13]
 [ 0 14 10 20  0]]
enter the even numbers: 17


In [ ]:
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
sum4_1=np.sum(arr4_1)
mean_cols4_3=np.mean(arr4_1,axis=0)
max_rows4_3=np.max(arr4_1,axis=1)
std4_4=np.std(arr4_1)
print("sum of the elements:",sum4_1)
print("mean of each coloumn:",mean_cols4_3)
print("max of each row:",max_rows4_3)
print("standard deviation:",mean_cols4_3)


--- Task 4: Aggregation Functions ---
sum of the elements: 84
mean of each coloumn: [11.          6.66666667 10.33333333]
max of each row: [12 15 20]
standard deviation: [11.          6.66666667 10.33333333]


In [ ]:
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

reshaped_arr5_2=np.arange(24).reshape((4,6))
reshaped_arr5_3=np.arange(24).reshape((2,3,4))
flattened_arr5_4=reshaped_arr5_2.ravel()
print("reshaped_arr5_2:\n",reshaped_arr5_2)
print("reshaped_arr5_3:\n",reshaped_arr5_3)
print("flattened",flattened_arr5_4)


--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_1=np.array(arr6_1 +scalar)
result6_2=np.array(arr6_1+vector)
print("adding scalar ",result6_1)
print("adding vector",result6_2)


--- Task 6: Broadcasting ---
adding scalar  [[11 12 13]
 [14 15 16]
 [17 18 19]]
adding vector [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [ ]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7.copy()
view_arr7[0]=99
print("original after view change",view_arr7)
copy_arr7=original_arr7.copy()
copy_arr7[4]=0
print("original",copy_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
original after view change [99  2  3  4  5]
original [1 2 3 4 0]


In [ ]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])
vstack_arr8_1=np.vstack((arr8_a,arr8_b))
hstack=np.hstack((arr8_a,arr8_b))
combined_arr8_3=np.vstack((vstack_arr8_1,arr8_c))
part1,part2,part3,part4,part5=np.split(combined_arr8_3,5)
print("vstack",vstack_arr8_1)
print("hstack",hstack)
print("combined",combined_arr8_3)
print("split",part1,part2,part3,part4,part5)


--- Task 8: Stacking and Splitting Arrays ---
vstack [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack [[1 2 5 6]
 [3 4 7 8]]
combined [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
split [[1 2]] [[3 4]] [[5 6]] [[7 8]] [[ 9 10]]


In [ ]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
sorted_arr9_1=np.sort(arr9_1)
sorted_cols9_2=np.sort(arr9_2d,axis=1)
idx9_3=np.where(arr9_1==9)
max_idx9_4=np.max(arr9_1)
print("sorting",sorted_arr9_1)
print("coloumn",sorted_cols9_2)
print("index",idx9_3)
print("maximum",max_idx9_4)



--- Task 9: Sorting and Searching ---
sorting [1 2 3 4 5 6 7 8 9]
coloumn [[10 20 30]
 [40 50 60]
 [70 80 90]]
index (array([4]),)
maximum 9
