<a href="https://colab.research.google.com/github/25wh1a0518/NASSCOM/blob/main/WEEK_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np


arr1 = np.arange(0, 10, 4) #arange
print("Array using arange:", arr1)

# linspace()
arr2 = np.linspace(0, 1, 8)
print("Array using linspace:", arr2)

arr3 = np.arange(1, 13).reshape((4, 3))#Reshape
print("Reshaped Array (3x3):\n", arr3)

# flatten()
print("Flattened version:", arr3.flatten())


Array using arange: [0 4 8]
Array using linspace: [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
Reshaped Array (3x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flattened version: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
import numpy as np

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)

print("Sum of all elements:", np.sum(data))             # Total sum
print("Column-wise sum:", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean:", np.mean(data, axis=1))          # Average of each row
print("Max value:", np.max(data))                       # Maximum value
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))              # Spread of values




Original Data:
 [[5 8 9]
 [2 4 6]]
Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9
Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [16]:
import numpy as np

a = np.array([3, 1, 7, 2, 9])
print("Original Array:",a)

# Sort array values
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 7)
print("Indices where value > 7:", idx)
print("Values > 4:", a[idx])

Original Array: [3 1 7 2 9]
Sorted Array: [1 2 3 7 9]
Indices where value > 7: (array([4]),)
Values > 4: [9]


In [20]:
import numpy as np

A = np.array([[1,4,8],[2,4,7]])
B = np.array([9,3,5])

print("matrix A:",A)
print("vector:",B)

C=A+B
print("value of C is:",C)



matrix A: [[1 4 8]
 [2 4 7]]
vector: [9 3 5]
value of C is: [[10  7 13]
 [11  7 12]]


In [24]:
nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 2
print("Mask (nums >2):", mask)

filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)


Mask (nums >2): [False False  True  True  True]
Filtered values: [3 4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [27]:
arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[2] = 99  # This change affects original
print("Original After View Change:", arr_orig)



Original After View Change: [10 20 99]


In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])

v_stack = np.vstack((x,y))
h_stack = np.hstack((x,y))

print("vertical stack:",v_stack)
print("horiaontal stack:",h_stack)

z=np.arange(12)
split_arr= np.array_split(z,4)
print("array split:", split_arr)

vertical stack: [[1 2 3]
 [4 5 6]]
horiaontal stack: [1 2 3 4 5 6]
array split: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [35]:
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(4)
print("Seeded Random Number:", np.random.rand())


Random Choices: [1 1 5 7 5]
Seeded Random Number: 0.9670298390136767


In [38]:
arr = np.array([10,34,56,20,43,78,65])
print("original array:",arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

original array: [10 34 56 20 43 78 65]
Element at index 0: 10
Element at last index: 65
Slice from index 1 to 4: [34 56 20]
Every second element: [10 56 43 65]
Reversed array: [65 78 43 20 56 34 10]


In [44]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

print("Element at (1,2):", matrix[1, 2])

print("First row:", matrix[2, :])

print("Second column:", matrix[:, 1])

print("Top-left 2x2 block:\n", matrix[:2, :2])


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [7 8 9]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [45]:
arr = np.array([5, 10, 15, 20, 25, 30])

mask = arr > 15
print("Boolean Mask:", mask)

print("Values greater than 15:", arr[mask])

print("Even numbers > 10:", arr[(arr > 5) & (arr % 2 == 0)])


Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [10 20 30]
